// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishAttempt = `-- name: FinishAttempt :one
UPDATE attempts SET finished_at = now()
WHERE id = $1 AND finished_at IS NULL
RETURNING id, assignment_id, test_id, student_id, started_at, finished_at
`

func (q *Queries) FinishAttempt(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, finishAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TestID,
		&i.StudentID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, assignment_id, test_id, student_id, started_at, finished_at FROM attempts WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TestID,
		&i.StudentID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAnswersForAttempt = `-- name: ListAnswersForAttempt :many
SELECT id, attempt_id, task_id, raw_answer, is_correct, time_spent_ms, answered_at FROM answers WHERE attempt_id = $1 ORDER BY answered_at
`

func (q *Queries) ListAnswersForAttempt(ctx context.Context, attemptID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersForAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.TaskID,
			&i.RawAnswer,
			&i.IsCorrect,
			&i.TimeSpentMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsForStudent = `-- name: ListAttemptsForStudent :many
SELECT att.id, att.test_id, att.started_at, att.finished_at,
       t.title, t.kind, t.subject_id,
       count(ans.id)                              AS total,
       count(ans.id) FILTER (WHERE ans.is_correct) AS correct,
       coalesce(sum(ans.time_spent_ms), 0)::bigint AS time_ms
FROM attempts att
JOIN tests t       ON t.id = att.test_id
LEFT JOIN answers ans ON ans.attempt_id = att.id
WHERE att.student_id = $1
GROUP BY att.id, t.title, t.kind, t.subject_id
ORDER BY att.started_at DESC
LIMIT $2
`

type ListAttemptsForStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	Limit     int32     `json:"limit"`
}

type ListAttemptsForStudentRow struct {
	ID         uuid.UUID  `json:"id"`
	TestID     uuid.UUID  `json:"test_id"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	Title      string     `json:"title"`
	Kind       string     `json:"kind"`
	SubjectID  uuid.UUID  `json:"subject_id"`
	Total      int64      `json:"total"`
	Correct    int64      `json:"correct"`
	TimeMs     int64      `json:"time_ms"`
}

// Attempts feed ("Недавние решения" / "Свежие попытки") with per-attempt score.
func (q *Queries) ListAttemptsForStudent(ctx context.Context, arg ListAttemptsForStudentParams) ([]ListAttemptsForStudentRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsForStudent, arg.StudentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsForStudentRow{}
	for rows.Next() {
		var i ListAttemptsForStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Title,
			&i.Kind,
			&i.SubjectID,
			&i.Total,
			&i.Correct,
			&i.TimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnswer = `-- name: RecordAnswer :one
INSERT INTO answers (attempt_id, task_id, raw_answer, is_correct, time_spent_ms)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, attempt_id, task_id, raw_answer, is_correct, time_spent_ms, answered_at
`

type RecordAnswerParams struct {
	AttemptID   uuid.UUID `json:"attempt_id"`
	TaskID      uuid.UUID `json:"task_id"`
	RawAnswer   string    `json:"raw_answer"`
	IsCorrect   bool      `json:"is_correct"`
	TimeSpentMs int64     `json:"time_spent_ms"`
}

func (q *Queries) RecordAnswer(ctx context.Context, arg RecordAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, recordAnswer,
		arg.AttemptID,
		arg.TaskID,
		arg.RawAnswer,
		arg.IsCorrect,
		arg.TimeSpentMs,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TaskID,
		&i.RawAnswer,
		&i.IsCorrect,
		&i.TimeSpentMs,
		&i.AnsweredAt,
	)
	return i, err
}

const startAttempt = `-- name: StartAttempt :one
INSERT INTO attempts (assignment_id, test_id, student_id)
VALUES ($1, $2, $3)
RETURNING id, assignment_id, test_id, student_id, started_at, finished_at
`

type StartAttemptParams struct {
	AssignmentID *uuid.UUID `json:"assignment_id"`
	TestID       uuid.UUID  `json:"test_id"`
	StudentID    uuid.UUID  `json:"student_id"`
}

func (q *Queries) StartAttempt(ctx context.Context, arg StartAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, startAttempt, arg.AssignmentID, arg.TestID, arg.StudentID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TestID,
		&i.StudentID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
