// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_sync.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBankSyncJob = `-- name: CancelBankSyncJob :one
UPDATE bank_sync_jobs SET state = CASE WHEN state IN ('queued', 'running') THEN 'cancelled' ELSE state END,
    finished_at = CASE WHEN state IN ('queued', 'running') THEN now() ELSE finished_at END,
    lease_until = NULL
WHERE id = $1 RETURNING id, subject, number, task_limit, active, kind, state, created_at, started_at, finished_at, lease_until, attempts, result, error
`

func (q *Queries) CancelBankSyncJob(ctx context.Context, id uuid.UUID) (BankSyncJob, error) {
	row := q.db.QueryRow(ctx, cancelBankSyncJob, id)
	var i BankSyncJob
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Number,
		&i.TaskLimit,
		&i.Active,
		&i.Kind,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseUntil,
		&i.Attempts,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const claimBankSyncJob = `-- name: ClaimBankSyncJob :one
UPDATE bank_sync_jobs SET state = 'running', started_at = now(), attempts = attempts + 1,
    lease_until = now() + interval '6 minutes'
WHERE id = (
    SELECT j.id FROM bank_sync_jobs j
    WHERE j.state = 'queued'
      AND (SELECT count(*) FROM bank_sync_jobs WHERE state = 'running') < 2
      AND NOT EXISTS (SELECT 1 FROM bank_sync_jobs r WHERE r.state = 'running' AND r.subject = j.subject)
    ORDER BY j.created_at LIMIT 1 FOR UPDATE SKIP LOCKED
) RETURNING id, subject, number, task_limit, active, kind, state, created_at, started_at, finished_at, lease_until, attempts, result, error
`

func (q *Queries) ClaimBankSyncJob(ctx context.Context) (BankSyncJob, error) {
	row := q.db.QueryRow(ctx, claimBankSyncJob)
	var i BankSyncJob
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Number,
		&i.TaskLimit,
		&i.Active,
		&i.Kind,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseUntil,
		&i.Attempts,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const countPendingBankSyncJobs = `-- name: CountPendingBankSyncJobs :one
SELECT count(*) FROM bank_sync_jobs WHERE state IN ('queued', 'running')
`

func (q *Queries) CountPendingBankSyncJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingBankSyncJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishBankSyncJob = `-- name: FinishBankSyncJob :exec
UPDATE bank_sync_jobs SET state = $3, result = $4, error = $5, finished_at = now(), lease_until = NULL
WHERE id = $1 AND attempts = $2 AND state = 'running'
`

type FinishBankSyncJobParams struct {
	ID       uuid.UUID `json:"id"`
	Attempts int32     `json:"attempts"`
	State    string    `json:"state"`
	Result   []byte    `json:"result"`
	Error    string    `json:"error"`
}

func (q *Queries) FinishBankSyncJob(ctx context.Context, arg FinishBankSyncJobParams) error {
	_, err := q.db.Exec(ctx, finishBankSyncJob,
		arg.ID,
		arg.Attempts,
		arg.State,
		arg.Result,
		arg.Error,
	)
	return err
}

const getBankSyncJob = `-- name: GetBankSyncJob :one
SELECT id, subject, number, task_limit, active, kind, state, created_at, started_at, finished_at, lease_until, attempts, result, error FROM bank_sync_jobs WHERE id = $1
`

func (q *Queries) GetBankSyncJob(ctx context.Context, id uuid.UUID) (BankSyncJob, error) {
	row := q.db.QueryRow(ctx, getBankSyncJob, id)
	var i BankSyncJob
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Number,
		&i.TaskLimit,
		&i.Active,
		&i.Kind,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseUntil,
		&i.Attempts,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const insertBankSyncJob = `-- name: InsertBankSyncJob :one
INSERT INTO bank_sync_jobs(subject, number, task_limit, active, kind) VALUES ($1, $2, $3, $4, $5) RETURNING id, subject, number, task_limit, active, kind, state, created_at, started_at, finished_at, lease_until, attempts, result, error
`

type InsertBankSyncJobParams struct {
	Subject   string `json:"subject"`
	Number    int32  `json:"number"`
	TaskLimit int32  `json:"task_limit"`
	Active    bool   `json:"active"`
	Kind      string `json:"kind"`
}

func (q *Queries) InsertBankSyncJob(ctx context.Context, arg InsertBankSyncJobParams) (BankSyncJob, error) {
	row := q.db.QueryRow(ctx, insertBankSyncJob,
		arg.Subject,
		arg.Number,
		arg.TaskLimit,
		arg.Active,
		arg.Kind,
	)
	var i BankSyncJob
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Number,
		&i.TaskLimit,
		&i.Active,
		&i.Kind,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseUntil,
		&i.Attempts,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const pruneBankSyncJobs = `-- name: PruneBankSyncJobs :exec
DELETE FROM bank_sync_jobs WHERE state NOT IN ('queued', 'running') AND finished_at < now() - interval '7 days'
`

func (q *Queries) PruneBankSyncJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneBankSyncJobs)
	return err
}

const reapBankSyncJobs = `-- name: ReapBankSyncJobs :exec
UPDATE bank_sync_jobs
SET state = CASE WHEN attempts < 3 THEN 'queued' ELSE 'failed' END,
    started_at = NULL, lease_until = NULL,
    finished_at = CASE WHEN attempts >= 3 THEN now() ELSE NULL END,
    error = CASE WHEN attempts >= 3 THEN 'Обновление прервано перезапуском сервиса. Повторите позже.' ELSE '' END
WHERE state = 'running' AND lease_until < now()
`

func (q *Queries) ReapBankSyncJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reapBankSyncJobs)
	return err
}

const recentBankSyncJob = `-- name: RecentBankSyncJob :one
SELECT id, subject, number, task_limit, active, kind, state, created_at, started_at, finished_at, lease_until, attempts, result, error FROM bank_sync_jobs
WHERE subject = $1 AND number = $2 AND active = $3
  AND (state IN ('queued', 'running') OR created_at >= $4)
  AND kind = $5
ORDER BY (state IN ('queued', 'running')) DESC, created_at DESC LIMIT 1
`

type RecentBankSyncJobParams struct {
	Subject   string    `json:"subject"`
	Number    int32     `json:"number"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	Kind      string    `json:"kind"`
}

func (q *Queries) RecentBankSyncJob(ctx context.Context, arg RecentBankSyncJobParams) (BankSyncJob, error) {
	row := q.db.QueryRow(ctx, recentBankSyncJob,
		arg.Subject,
		arg.Number,
		arg.Active,
		arg.CreatedAt,
		arg.Kind,
	)
	var i BankSyncJob
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Number,
		&i.TaskLimit,
		&i.Active,
		&i.Kind,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseUntil,
		&i.Attempts,
		&i.Result,
		&i.Error,
	)
	return i, err
}
