// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addClassMember = `-- name: AddClassMember :exec
INSERT INTO class_members (class_id, student_id) VALUES ($1, $2)
ON CONFLICT (class_id, student_id) DO NOTHING
`

type AddClassMemberParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) AddClassMember(ctx context.Context, arg AddClassMemberParams) error {
	_, err := q.db.Exec(ctx, addClassMember, arg.ClassID, arg.StudentID)
	return err
}

const classMastery = `-- name: ClassMastery :many
SELECT att.student_id, t.number,
       count(*)                             AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE t.subject_id = $2
  AND att.student_id IN (SELECT student_id FROM class_members WHERE class_id = $1)
GROUP BY att.student_id, t.number
ORDER BY att.student_id, t.number
`

type ClassMasteryParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type ClassMasteryRow struct {
	StudentID uuid.UUID `json:"student_id"`
	Number    int32     `json:"number"`
	Total     int64     `json:"total"`
	Correct   int64     `json:"correct"`
}

// The class overview grid: per-member per-number success for one subject.
func (q *Queries) ClassMastery(ctx context.Context, arg ClassMasteryParams) ([]ClassMasteryRow, error) {
	rows, err := q.db.Query(ctx, classMastery, arg.ClassID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassMasteryRow{}
	for rows.Next() {
		var i ClassMasteryRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Number,
			&i.Total,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (teacher_id, name) VALUES ($1, $2) RETURNING id, teacher_id, name, created_at
`

type CreateClassParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass, arg.TeacherID, arg.Name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :execrows
DELETE FROM classes WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClass, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClass = `-- name: GetClass :one
SELECT id, teacher_id, name, created_at FROM classes WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id uuid.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAllClasses = `-- name: ListAllClasses :many
SELECT c.id, c.teacher_id, c.name, c.created_at, u.name AS teacher_name, count(cm.id) AS member_count
FROM classes c
JOIN users u ON u.id = c.teacher_id
LEFT JOIN class_members cm ON cm.class_id = c.id
GROUP BY c.id, u.name
ORDER BY u.name, c.name
`

type ListAllClassesRow struct {
	ID          uuid.UUID `json:"id"`
	TeacherID   uuid.UUID `json:"teacher_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	TeacherName string    `json:"teacher_name"`
	MemberCount int64     `json:"member_count"`
}

// Admin view: every class with its teacher's name.
func (q *Queries) ListAllClasses(ctx context.Context) ([]ListAllClassesRow, error) {
	rows, err := q.db.Query(ctx, listAllClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllClassesRow{}
	for rows.Next() {
		var i ListAllClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.CreatedAt,
			&i.TeacherName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassMembers = `-- name: ListClassMembers :many
SELECT u.id, u.role, u.telegram_id, u.name, u.created_at, u.username, u.password_hash, u.is_active, u.subject FROM users u
JOIN class_members cm ON cm.student_id = u.id
WHERE cm.class_id = $1
ORDER BY u.name
`

func (q *Queries) ListClassMembers(ctx context.Context, classID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listClassMembers, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsActive,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassMembershipsForTeacher = `-- name: ListClassMembershipsForTeacher :many
SELECT cm.student_id, c.id AS class_id, c.name AS class_name
FROM class_members cm
JOIN classes c ON c.id = cm.class_id
WHERE c.teacher_id = $1
ORDER BY c.name
`

type ListClassMembershipsForTeacherRow struct {
	StudentID uuid.UUID `json:"student_id"`
	ClassID   uuid.UUID `json:"class_id"`
	ClassName string    `json:"class_name"`
}

// All (student, class) pairs across one teacher's classes, to tag the teacher's
// student list with class names in one query.
func (q *Queries) ListClassMembershipsForTeacher(ctx context.Context, teacherID uuid.UUID) ([]ListClassMembershipsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listClassMembershipsForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassMembershipsForTeacherRow{}
	for rows.Next() {
		var i ListClassMembershipsForTeacherRow
		if err := rows.Scan(&i.StudentID, &i.ClassID, &i.ClassName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForStudent = `-- name: ListClassesForStudent :many
SELECT c.id, c.teacher_id, c.name, c.created_at, u.name AS teacher_name
FROM classes c
JOIN class_members cm ON cm.class_id = c.id
JOIN users u ON u.id = c.teacher_id
WHERE cm.student_id = $1
ORDER BY c.name
`

type ListClassesForStudentRow struct {
	ID          uuid.UUID `json:"id"`
	TeacherID   uuid.UUID `json:"teacher_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	TeacherName string    `json:"teacher_name"`
}

// The student's profile: which classes (and whose) they belong to.
func (q *Queries) ListClassesForStudent(ctx context.Context, studentID uuid.UUID) ([]ListClassesForStudentRow, error) {
	rows, err := q.db.Query(ctx, listClassesForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesForStudentRow{}
	for rows.Next() {
		var i ListClassesForStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.CreatedAt,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForTeacher = `-- name: ListClassesForTeacher :many
SELECT c.id, c.teacher_id, c.name, c.created_at, count(cm.id) AS member_count
FROM classes c
LEFT JOIN class_members cm ON cm.class_id = c.id
WHERE c.teacher_id = $1
GROUP BY c.id
ORDER BY c.name
`

type ListClassesForTeacherRow struct {
	ID          uuid.UUID `json:"id"`
	TeacherID   uuid.UUID `json:"teacher_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	MemberCount int64     `json:"member_count"`
}

func (q *Queries) ListClassesForTeacher(ctx context.Context, teacherID uuid.UUID) ([]ListClassesForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listClassesForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesForTeacherRow{}
	for rows.Next() {
		var i ListClassesForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassMember = `-- name: RemoveClassMember :execrows
DELETE FROM class_members WHERE class_id = $1 AND student_id = $2
`

type RemoveClassMemberParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) RemoveClassMember(ctx context.Context, arg RemoveClassMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeClassMember, arg.ClassID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameClass = `-- name: RenameClass :one
UPDATE classes SET name = $2 WHERE id = $1 RETURNING id, teacher_id, name, created_at
`

type RenameClassParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameClass(ctx context.Context, arg RenameClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, renameClass, arg.ID, arg.Name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
