// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

// Exact badge count (the list itself is limit-bounded).
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, kind, assignment_id)
VALUES ($1, $2, $3)
`

type CreateNotificationParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Kind         string    `json:"kind"`
	AssignmentID uuid.UUID `json:"assignment_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification, arg.UserID, arg.Kind, arg.AssignmentID)
	return err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT n.id, n.kind, n.assignment_id, n.read_at, n.created_at,
       a.test_id, a.student_id, a.scheduled_at, a.status AS assignment_status,
       t.title AS test_title, t.subject_id,
       su.name AS student_name
FROM notifications n
JOIN assignments a ON a.id = n.assignment_id
JOIN tests t ON t.id = a.test_id
JOIN users su ON su.id = a.student_id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2
`

type ListNotificationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListNotificationsForUserRow struct {
	ID               uuid.UUID  `json:"id"`
	Kind             string     `json:"kind"`
	AssignmentID     uuid.UUID  `json:"assignment_id"`
	ReadAt           *time.Time `json:"read_at"`
	CreatedAt        time.Time  `json:"created_at"`
	TestID           uuid.UUID  `json:"test_id"`
	StudentID        uuid.UUID  `json:"student_id"`
	ScheduledAt      time.Time  `json:"scheduled_at"`
	AssignmentStatus string     `json:"assignment_status"`
	TestTitle        string     `json:"test_title"`
	SubjectID        uuid.UUID  `json:"subject_id"`
	StudentName      string     `json:"student_name"`
}

// The web bell feed: notification joined with its assignment/test/student so
// the UI can render «назначен тест …» / «N решил тест …» and jump to the test.
func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]ListNotificationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsForUserRow{}
	for rows.Next() {
		var i ListNotificationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AssignmentID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.TestID,
			&i.StudentID,
			&i.ScheduledAt,
			&i.AssignmentStatus,
			&i.TestTitle,
			&i.SubjectID,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// user_id guards against marking someone else's notification.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
