// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (token, user_id, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token, user_id, created_by, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	Token     string     `json:"token"`
	UserID    uuid.UUID  `json:"user_id"`
	CreatedBy *uuid.UUID `json:"created_by"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.Token,
		arg.UserID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT token, user_id, created_by, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getValidPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE token = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, token)
	return err
}
