// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: solutions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addSolutionPhoto = `-- name: AddSolutionPhoto :one
INSERT INTO solution_photos (attempt_id, task_id, object_key, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5) RETURNING id, attempt_id, task_id, object_key, content_type, size_bytes, created_at
`

type AddSolutionPhotoParams struct {
	AttemptID   uuid.UUID `json:"attempt_id"`
	TaskID      uuid.UUID `json:"task_id"`
	ObjectKey   string    `json:"object_key"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
}

func (q *Queries) AddSolutionPhoto(ctx context.Context, arg AddSolutionPhotoParams) (SolutionPhoto, error) {
	row := q.db.QueryRow(ctx, addSolutionPhoto,
		arg.AttemptID,
		arg.TaskID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i SolutionPhoto
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TaskID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const claimPracticeFetch = `-- name: ClaimPracticeFetch :execrows
INSERT INTO practice_fetch_limits (subject_id) VALUES ($1)
ON CONFLICT (subject_id) DO UPDATE SET requested_at = now()
WHERE practice_fetch_limits.requested_at < now() - interval '2 minutes'
`

func (q *Queries) ClaimPracticeFetch(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimPracticeFetch, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createReviewNotification = `-- name: CreateReviewNotification :exec
INSERT INTO notifications (user_id, kind, assignment_id, attempt_id)
VALUES ($1, 'attempt_reviewed', $2, $3)
`

type CreateReviewNotificationParams struct {
	UserID       uuid.UUID  `json:"user_id"`
	AssignmentID *uuid.UUID `json:"assignment_id"`
	AttemptID    *uuid.UUID `json:"attempt_id"`
}

func (q *Queries) CreateReviewNotification(ctx context.Context, arg CreateReviewNotificationParams) error {
	_, err := q.db.Exec(ctx, createReviewNotification, arg.UserID, arg.AssignmentID, arg.AttemptID)
	return err
}

const deleteSolutionPhoto = `-- name: DeleteSolutionPhoto :exec
DELETE FROM solution_photos WHERE id = $1
`

func (q *Queries) DeleteSolutionPhoto(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSolutionPhoto, id)
	return err
}

const getSolutionPhoto = `-- name: GetSolutionPhoto :one
SELECT id, attempt_id, task_id, object_key, content_type, size_bytes, created_at FROM solution_photos WHERE id = $1
`

func (q *Queries) GetSolutionPhoto(ctx context.Context, id uuid.UUID) (SolutionPhoto, error) {
	row := q.db.QueryRow(ctx, getSolutionPhoto, id)
	var i SolutionPhoto
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TaskID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const gradeAnswer = `-- name: GradeAnswer :one
UPDATE answers SET points = $3, teacher_comment = $4, review_status = 'reviewed',
    reviewed_by = $5, reviewed_at = now(), is_correct = ($3 = max_points)
WHERE attempt_id = $1 AND id = $2 AND review_status IN ('pending', 'reviewed') RETURNING id, attempt_id, task_id, raw_answer, is_correct, time_spent_ms, answered_at, review_status, points, max_points, teacher_comment, reviewed_by, reviewed_at
`

type GradeAnswerParams struct {
	AttemptID      uuid.UUID  `json:"attempt_id"`
	ID             uuid.UUID  `json:"id"`
	Points         *int32     `json:"points"`
	TeacherComment string     `json:"teacher_comment"`
	ReviewedBy     *uuid.UUID `json:"reviewed_by"`
}

func (q *Queries) GradeAnswer(ctx context.Context, arg GradeAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, gradeAnswer,
		arg.AttemptID,
		arg.ID,
		arg.Points,
		arg.TeacherComment,
		arg.ReviewedBy,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TaskID,
		&i.RawAnswer,
		&i.IsCorrect,
		&i.TimeSpentMs,
		&i.AnsweredAt,
		&i.ReviewStatus,
		&i.Points,
		&i.MaxPoints,
		&i.TeacherComment,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const insertSubmission = `-- name: InsertSubmission :one
INSERT INTO answers (attempt_id, task_id, raw_answer, is_correct, time_spent_ms, review_status, points, max_points)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, attempt_id, task_id, raw_answer, is_correct, time_spent_ms, answered_at, review_status, points, max_points, teacher_comment, reviewed_by, reviewed_at
`

type InsertSubmissionParams struct {
	AttemptID    uuid.UUID `json:"attempt_id"`
	TaskID       uuid.UUID `json:"task_id"`
	RawAnswer    string    `json:"raw_answer"`
	IsCorrect    bool      `json:"is_correct"`
	TimeSpentMs  int64     `json:"time_spent_ms"`
	ReviewStatus string    `json:"review_status"`
	Points       *int32    `json:"points"`
	MaxPoints    int32     `json:"max_points"`
}

func (q *Queries) InsertSubmission(ctx context.Context, arg InsertSubmissionParams) (Answer, error) {
	row := q.db.QueryRow(ctx, insertSubmission,
		arg.AttemptID,
		arg.TaskID,
		arg.RawAnswer,
		arg.IsCorrect,
		arg.TimeSpentMs,
		arg.ReviewStatus,
		arg.Points,
		arg.MaxPoints,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TaskID,
		&i.RawAnswer,
		&i.IsCorrect,
		&i.TimeSpentMs,
		&i.AnsweredAt,
		&i.ReviewStatus,
		&i.Points,
		&i.MaxPoints,
		&i.TeacherComment,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const listSolutionPhotos = `-- name: ListSolutionPhotos :many
SELECT id, attempt_id, task_id, object_key, content_type, size_bytes, created_at FROM solution_photos WHERE attempt_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListSolutionPhotos(ctx context.Context, attemptID uuid.UUID) ([]SolutionPhoto, error) {
	rows, err := q.db.Query(ctx, listSolutionPhotos, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SolutionPhoto{}
	for rows.Next() {
		var i SolutionPhoto
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.TaskID,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttempt = `-- name: LockAttempt :one
SELECT id, assignment_id, test_id, student_id, started_at, finished_at FROM attempts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAttempt(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, lockAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TestID,
		&i.StudentID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const recentNumberPerformance = `-- name: RecentNumberPerformance :many
WITH recent AS (
    SELECT t.number, a.is_correct,
           row_number() OVER (PARTITION BY t.number ORDER BY a.answered_at DESC, a.id) AS rank
    FROM answers a JOIN attempts att ON att.id = a.attempt_id JOIN tasks t ON t.id = a.task_id
    WHERE att.student_id = $1 AND t.subject_id = $2 AND a.review_status <> 'pending'
)
SELECT number, count(*) AS total, count(*) FILTER (WHERE is_correct) AS correct
FROM recent WHERE rank <= 10 GROUP BY number ORDER BY number
`

type RecentNumberPerformanceParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type RecentNumberPerformanceRow struct {
	Number  int32 `json:"number"`
	Total   int64 `json:"total"`
	Correct int64 `json:"correct"`
}

func (q *Queries) RecentNumberPerformance(ctx context.Context, arg RecentNumberPerformanceParams) ([]RecentNumberPerformanceRow, error) {
	rows, err := q.db.Query(ctx, recentNumberPerformance, arg.StudentID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentNumberPerformanceRow{}
	for rows.Next() {
		var i RecentNumberPerformanceRow
		if err := rows.Scan(&i.Number, &i.Total, &i.Correct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
