// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answersOnDay = `-- name: AnswersOnDay :many
SELECT a.id, a.task_id, a.raw_answer, a.is_correct, a.time_spent_ms, a.answered_at,
       t.number, t.subject_id
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE att.student_id = $1
  AND a.answered_at >= $2
  AND a.answered_at <  $3
ORDER BY a.answered_at
`

type AnswersOnDayParams struct {
	StudentID uuid.UUID `json:"student_id"`
	DayStart  time.Time `json:"day_start"`
	DayEnd    time.Time `json:"day_end"`
}

type AnswersOnDayRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	RawAnswer   string    `json:"raw_answer"`
	IsCorrect   bool      `json:"is_correct"`
	TimeSpentMs int64     `json:"time_spent_ms"`
	AnsweredAt  time.Time `json:"answered_at"`
	Number      int32     `json:"number"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

// Heatmap drill-down: what was solved on a given day.
func (q *Queries) AnswersOnDay(ctx context.Context, arg AnswersOnDayParams) ([]AnswersOnDayRow, error) {
	rows, err := q.db.Query(ctx, answersOnDay, arg.StudentID, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnswersOnDayRow{}
	for rows.Next() {
		var i AnswersOnDayRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RawAnswer,
			&i.IsCorrect,
			&i.TimeSpentMs,
			&i.AnsweredAt,
			&i.Number,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heatmapForStudent = `-- name: HeatmapForStudent :many
SELECT date_trunc('day', a.answered_at)::date AS day,
       count(*)                          AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
WHERE att.student_id = $1
  AND a.answered_at >= $2
GROUP BY day
ORDER BY day
`

type HeatmapForStudentParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	AnsweredAt time.Time `json:"answered_at"`
}

type HeatmapForStudentRow struct {
	Day     pgtype.Date `json:"day"`
	Total   int64       `json:"total"`
	Correct int64       `json:"correct"`
}

// Activity per day (github-style heatmap): total answers and how many correct.
func (q *Queries) HeatmapForStudent(ctx context.Context, arg HeatmapForStudentParams) ([]HeatmapForStudentRow, error) {
	rows, err := q.db.Query(ctx, heatmapForStudent, arg.StudentID, arg.AnsweredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeatmapForStudentRow{}
	for rows.Next() {
		var i HeatmapForStudentRow
		if err := rows.Scan(&i.Day, &i.Total, &i.Correct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masteryByNumber = `-- name: MasteryByNumber :many
SELECT t.number,
       count(*)                          AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct,
       avg(a.time_spent_ms)::bigint      AS avg_time_ms
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE att.student_id = $1 AND t.subject_id = $2
GROUP BY t.number
ORDER BY t.number
`

type MasteryByNumberParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type MasteryByNumberRow struct {
	Number    int32 `json:"number"`
	Total     int64 `json:"total"`
	Correct   int64 `json:"correct"`
	AvgTimeMs int64 `json:"avg_time_ms"`
}

// Success per task number for a subject (per-task mastery grid).
func (q *Queries) MasteryByNumber(ctx context.Context, arg MasteryByNumberParams) ([]MasteryByNumberRow, error) {
	rows, err := q.db.Query(ctx, masteryByNumber, arg.StudentID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasteryByNumberRow{}
	for rows.Next() {
		var i MasteryByNumberRow
		if err := rows.Scan(
			&i.Number,
			&i.Total,
			&i.Correct,
			&i.AvgTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masterySeries = `-- name: MasterySeries :many
SELECT t.number,
       date_trunc('week', a.answered_at)::date AS week,
       count(*)                          AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE att.student_id = $1 AND t.subject_id = $2
GROUP BY t.number, week
ORDER BY t.number, week
`

type MasterySeriesParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type MasterySeriesRow struct {
	Number  int32       `json:"number"`
	Week    pgtype.Date `json:"week"`
	Total   int64       `json:"total"`
	Correct int64       `json:"correct"`
}

// Per-number success over time (weekly buckets) for the mastery line chart.
func (q *Queries) MasterySeries(ctx context.Context, arg MasterySeriesParams) ([]MasterySeriesRow, error) {
	rows, err := q.db.Query(ctx, masterySeries, arg.StudentID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterySeriesRow{}
	for rows.Next() {
		var i MasterySeriesRow
		if err := rows.Scan(
			&i.Number,
			&i.Week,
			&i.Total,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformStats = `-- name: PlatformStats :one
SELECT
    (SELECT count(*) FROM users WHERE role = 'student')          AS students,
    (SELECT count(*) FROM users WHERE role = 'teacher')          AS teachers,
    (SELECT count(*) FROM users WHERE role = 'admin')            AS admins,
    (SELECT count(*) FROM users WHERE NOT is_active)             AS inactive_users,
    (SELECT count(*) FROM classes)                               AS classes,
    (SELECT count(*) FROM tasks)                                 AS tasks,
    (SELECT count(*) FROM tasks WHERE status = 'active')         AS active_tasks,
    (SELECT count(*) FROM tests WHERE title <> '__practice__')   AS tests,
    (SELECT count(*) FROM assignments)                           AS assignments,
    (SELECT count(*) FROM attempts)                              AS attempts,
    (SELECT count(*) FROM answers)                               AS answers,
    (SELECT count(*) FROM answers WHERE is_correct)              AS correct_answers,
    (SELECT count(*) FROM answers
      WHERE answered_at >= now() - interval '7 days')            AS answers_7d
`

type PlatformStatsRow struct {
	Students       int64 `json:"students"`
	Teachers       int64 `json:"teachers"`
	Admins         int64 `json:"admins"`
	InactiveUsers  int64 `json:"inactive_users"`
	Classes        int64 `json:"classes"`
	Tasks          int64 `json:"tasks"`
	ActiveTasks    int64 `json:"active_tasks"`
	Tests          int64 `json:"tests"`
	Assignments    int64 `json:"assignments"`
	Attempts       int64 `json:"attempts"`
	Answers        int64 `json:"answers"`
	CorrectAnswers int64 `json:"correct_answers"`
	Answers7d      int64 `json:"answers_7d"`
}

// Platform-wide counters for the admin dashboard.
func (q *Queries) PlatformStats(ctx context.Context) (PlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, platformStats)
	var i PlatformStatsRow
	err := row.Scan(
		&i.Students,
		&i.Teachers,
		&i.Admins,
		&i.InactiveUsers,
		&i.Classes,
		&i.Tasks,
		&i.ActiveTasks,
		&i.Tests,
		&i.Assignments,
		&i.Attempts,
		&i.Answers,
		&i.CorrectAnswers,
		&i.Answers7d,
	)
	return i, err
}

const subjectAccuracy = `-- name: SubjectAccuracy :one
SELECT count(*)                          AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE att.student_id = $1 AND t.subject_id = $2
`

type SubjectAccuracyParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type SubjectAccuracyRow struct {
	Total   int64 `json:"total"`
	Correct int64 `json:"correct"`
}

// Overall success rate for a subject: input to the score forecast (§11 M5).
func (q *Queries) SubjectAccuracy(ctx context.Context, arg SubjectAccuracyParams) (SubjectAccuracyRow, error) {
	row := q.db.QueryRow(ctx, subjectAccuracy, arg.StudentID, arg.SubjectID)
	var i SubjectAccuracyRow
	err := row.Scan(&i.Total, &i.Correct)
	return i, err
}

const subjectActivityStats = `-- name: SubjectActivityStats :many
SELECT s.code,
       (SELECT count(*) FROM tasks t
         WHERE t.subject_id = s.id AND t.status = 'active')      AS active_tasks,
       (SELECT count(*) FROM answers a
         JOIN tasks t ON t.id = a.task_id
        WHERE t.subject_id = s.id)                               AS answers,
       (SELECT count(*) FROM answers a
         JOIN tasks t ON t.id = a.task_id
        WHERE t.subject_id = s.id AND a.is_correct)              AS correct
FROM subjects s
ORDER BY s.code
`

type SubjectActivityStatsRow struct {
	Code        string `json:"code"`
	ActiveTasks int64  `json:"active_tasks"`
	Answers     int64  `json:"answers"`
	Correct     int64  `json:"correct"`
}

// Per-subject platform breakdown for the admin dashboard.
func (q *Queries) SubjectActivityStats(ctx context.Context) ([]SubjectActivityStatsRow, error) {
	rows, err := q.db.Query(ctx, subjectActivityStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectActivityStatsRow{}
	for rows.Next() {
		var i SubjectActivityStatsRow
		if err := rows.Scan(
			&i.Code,
			&i.ActiveTasks,
			&i.Answers,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weakSpots = `-- name: WeakSpots :many
SELECT t.number,
       count(*)                          AS total,
       count(*) FILTER (WHERE a.is_correct) AS correct,
       avg(a.time_spent_ms)::bigint      AS avg_time_ms
FROM answers a
JOIN attempts att ON att.id = a.attempt_id
JOIN tasks t      ON t.id = a.task_id
WHERE att.student_id = $1 AND t.subject_id = $2
GROUP BY t.number
HAVING count(*) >= $3
ORDER BY (count(*) FILTER (WHERE a.is_correct))::float / count(*) ASC
LIMIT $4
`

type WeakSpotsParams struct {
	StudentID   uuid.UUID   `json:"student_id"`
	SubjectID   uuid.UUID   `json:"subject_id"`
	MinAttempts interface{} `json:"min_attempts"`
	Lim         int32       `json:"lim"`
}

type WeakSpotsRow struct {
	Number    int32 `json:"number"`
	Total     int64 `json:"total"`
	Correct   int64 `json:"correct"`
	AvgTimeMs int64 `json:"avg_time_ms"`
}

// Worst task numbers by success rate (>= min attempts), for "слабые места".
func (q *Queries) WeakSpots(ctx context.Context, arg WeakSpotsParams) ([]WeakSpotsRow, error) {
	rows, err := q.db.Query(ctx, weakSpots,
		arg.StudentID,
		arg.SubjectID,
		arg.MinAttempts,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeakSpotsRow{}
	for rows.Next() {
		var i WeakSpotsRow
		if err := rows.Scan(
			&i.Number,
			&i.Total,
			&i.Correct,
			&i.AvgTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
