// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getSubject = `-- name: GetSubject :one
SELECT id, code, title FROM subjects WHERE id = $1
`

func (q *Queries) GetSubject(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Code, &i.Title)
	return i, err
}

const getSubjectByCode = `-- name: GetSubjectByCode :one
SELECT id, code, title FROM subjects WHERE code = $1
`

func (q *Queries) GetSubjectByCode(ctx context.Context, code string) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByCode, code)
	var i Subject
	err := row.Scan(&i.ID, &i.Code, &i.Title)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, code, title FROM subjects ORDER BY code
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Code, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
