// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const activateDraftTaskBySource = `-- name: ActivateDraftTaskBySource :execrows
UPDATE tasks SET status = 'active'
WHERE source ->> 'provider'  = $1::text
  AND source ->> 'extern_id' = $2::text
  AND status = 'draft'
`

type ActivateDraftTaskBySourceParams struct {
	Provider string `json:"provider"`
	ExternID string `json:"extern_id"`
}

// Promote a dedup-hit DRAFT to active (the builder path ingests as active, so a
// re-fetched task it needs must become usable). Drafts only — a task the
// teacher rejected stays rejected.
func (q *Queries) ActivateDraftTaskBySource(ctx context.Context, arg ActivateDraftTaskBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateDraftTaskBySource, arg.Provider, arg.ExternID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMistakeTasks = `-- name: CountMistakeTasks :one
SELECT count(*) FROM tasks t
JOIN LATERAL (
    SELECT a.is_correct
    FROM answers a
    JOIN attempts att ON att.id = a.attempt_id
    WHERE att.student_id = $1 AND a.task_id = t.id
    ORDER BY a.answered_at DESC
    LIMIT 1
) last ON NOT last.is_correct
WHERE t.subject_id = $2 AND t.status = 'active'
`

type CountMistakeTasksParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

// Size of the «работа над ошибками» queue (the dashboard badge).
func (q *Queries) CountMistakeTasks(ctx context.Context, arg CountMistakeTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMistakeTasks, arg.StudentID, arg.SubjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksBySubject = `-- name: CountTasksBySubject :one
SELECT COUNT(*) FROM tasks WHERE subject_id = $1
`

func (q *Queries) CountTasksBySubject(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (subject_id, number, statement, media, answer_schema, source, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, subject_id, number, statement, media, answer_schema, source, status, created_at
`

type CreateTaskParams struct {
	SubjectID    uuid.UUID `json:"subject_id"`
	Number       int32     `json:"number"`
	Statement    string    `json:"statement"`
	Media        []byte    `json:"media"`
	AnswerSchema []byte    `json:"answer_schema"`
	Source       []byte    `json:"source"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.SubjectID,
		arg.Number,
		arg.Statement,
		arg.Media,
		arg.AnswerSchema,
		arg.Source,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Number,
		&i.Statement,
		&i.Media,
		&i.AnswerSchema,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTestItemsForUnansweredTasksBySubject = `-- name: DeleteTestItemsForUnansweredTasksBySubject :exec
DELETE FROM test_items
WHERE task_id IN (
    SELECT id FROM tasks
    WHERE subject_id = $1
      AND NOT EXISTS (SELECT 1 FROM answers a WHERE a.task_id = tasks.id)
)
`

// Detach the about-to-be-cleared bank tasks from any tests first: test_items
// has no ON DELETE CASCADE to tasks, so it must go before the task delete.
// Only tasks with no recorded answers are touched (answered ones are kept).
func (q *Queries) DeleteTestItemsForUnansweredTasksBySubject(ctx context.Context, subjectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTestItemsForUnansweredTasksBySubject, subjectID)
	return err
}

const deleteUnansweredTasksBySubject = `-- name: DeleteUnansweredTasksBySubject :execrows
DELETE FROM tasks
WHERE subject_id = $1
  AND NOT EXISTS (SELECT 1 FROM answers a WHERE a.task_id = tasks.id)
`

// Clear the bank for a subject, preserving any task that carries student
// history (has a recorded answer) so attempts/stats never orphan.
func (q *Queries) DeleteUnansweredTasksBySubject(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnansweredTasksBySubject, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT id, subject_id, number, statement, media, answer_schema, source, status, created_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Number,
		&i.Statement,
		&i.Media,
		&i.AnswerSchema,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, subject_id, number, statement, media, answer_schema, source, status, created_at FROM tasks
WHERE ($3::uuid IS NULL OR subject_id = $3)
  AND ($4::int      IS NULL OR number = $4)
  AND ($5::text     IS NULL OR status = $5)
ORDER BY number, created_at DESC
LIMIT $1 OFFSET $2
`

type ListTasksParams struct {
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
	SubjectID *uuid.UUID `json:"subject_id"`
	Number    *int32     `json:"number"`
	Status    *string    `json:"status"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Limit,
		arg.Offset,
		arg.SubjectID,
		arg.Number,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Number,
			&i.Statement,
			&i.Media,
			&i.AnswerSchema,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mistakeTasks = `-- name: MistakeTasks :many
SELECT t.id, t.subject_id, t.number, t.statement, t.media, t.answer_schema, t.source, t.status, t.created_at FROM tasks t
JOIN LATERAL (
    SELECT a.is_correct, a.answered_at
    FROM answers a
    JOIN attempts att ON att.id = a.attempt_id
    WHERE att.student_id = $1 AND a.task_id = t.id
    ORDER BY a.answered_at DESC
    LIMIT 1
) last ON NOT last.is_correct
WHERE t.subject_id = $2 AND t.status = 'active'
ORDER BY last.answered_at
LIMIT $3
`

type MistakeTasksParams struct {
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Lim       int32     `json:"lim"`
}

// «Работа над ошибками»: active tasks whose LATEST answer by this student is
// wrong — answering one correctly (anywhere) drops it out of the queue.
// Oldest mistakes first, so nothing rots at the bottom.
func (q *Queries) MistakeTasks(ctx context.Context, arg MistakeTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, mistakeTasks, arg.StudentID, arg.SubjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Number,
			&i.Statement,
			&i.Media,
			&i.AnswerSchema,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const practiceNumbers = `-- name: PracticeNumbers :many
SELECT t.number,
       COUNT(*) FILTER (WHERE t.status = 'active')::bigint AS bank_active,
       COUNT(*) FILTER (WHERE t.status = 'active' AND st.correct_cnt >= $1::bigint)::bigint AS mastered,
       COALESCE(SUM(st.total_cnt), 0)::bigint   AS answers_total,
       COALESCE(SUM(st.correct_cnt), 0)::bigint AS answers_correct
FROM tasks t
LEFT JOIN LATERAL (
    SELECT count(*) AS total_cnt, count(*) FILTER (WHERE a.is_correct) AS correct_cnt
    FROM answers a
    JOIN attempts att ON att.id = a.attempt_id
    WHERE a.task_id = t.id AND att.student_id = $2
) st ON TRUE
WHERE t.subject_id = $3
GROUP BY t.number
ORDER BY t.number
`

type PracticeNumbersParams struct {
	Mastered  int64     `json:"mastered"`
	StudentID uuid.UUID `json:"student_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type PracticeNumbersRow struct {
	Number         int32 `json:"number"`
	BankActive     int64 `json:"bank_active"`
	Mastered       int64 `json:"mastered"`
	AnswersTotal   int64 `json:"answers_total"`
	AnswersCorrect int64 `json:"answers_correct"`
}

// The student's training map: per задание-номер, how many active tasks the bank
// holds, how many of those the student has mastered (solved correctly >=
// `mastered` times), and their lifetime answer accuracy on the number. Numbers
// whose tasks are all inactive still show as long as the rows exist, so history
// never disappears from the map.
func (q *Queries) PracticeNumbers(ctx context.Context, arg PracticeNumbersParams) ([]PracticeNumbersRow, error) {
	rows, err := q.db.Query(ctx, practiceNumbers, arg.Mastered, arg.StudentID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeNumbersRow{}
	for rows.Next() {
		var i PracticeNumbersRow
		if err := rows.Scan(
			&i.Number,
			&i.BankActive,
			&i.Mastered,
			&i.AnswersTotal,
			&i.AnswersCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const practiceTasks = `-- name: PracticeTasks :many
SELECT t.id, t.subject_id, t.number, t.statement, t.media, t.answer_schema, t.source, t.status, t.created_at FROM tasks t
WHERE t.subject_id = $1 AND t.status = 'active'
  AND ($2::int IS NULL OR t.number = $2)
  AND (
    SELECT count(*) FROM answers a
    JOIN attempts att ON att.id = a.attempt_id
    WHERE att.student_id = $3 AND a.task_id = t.id AND a.is_correct
  ) < $4::bigint
ORDER BY random()
LIMIT $5
`

type PracticeTasksParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Number    *int32    `json:"number"`
	StudentID uuid.UUID `json:"student_id"`
	Mastered  int64     `json:"mastered"`
	Lim       int32     `json:"lim"`
}

// Active tasks for a subject that the student has NOT yet solved correctly
// `mastered` times — so mastered tasks stop repeating in practice. Random order.
// An optional number narrows the pool to one задание (the server-side drill).
func (q *Queries) PracticeTasks(ctx context.Context, arg PracticeTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, practiceTasks,
		arg.SubjectID,
		arg.Number,
		arg.StudentID,
		arg.Mastered,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Number,
			&i.Statement,
			&i.Media,
			&i.AnswerSchema,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomTasksForNumber = `-- name: RandomTasksForNumber :many
SELECT id FROM tasks
WHERE subject_id = $1 AND number = $2 AND status = 'active'
ORDER BY random()
LIMIT $3
`

type RandomTasksForNumberParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Number    int32     `json:"number"`
	Limit     int32     `json:"limit"`
}

// N random active tasks of one number: a drill variant.
func (q *Queries) RandomTasksForNumber(ctx context.Context, arg RandomTasksForNumberParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomTasksForNumber, arg.SubjectID, arg.Number, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomTasksOnePerNumber = `-- name: RandomTasksOnePerNumber :many
SELECT DISTINCT ON (number) id, number
FROM tasks
WHERE subject_id = $1 AND status = 'active'
ORDER BY number, random()
`

type RandomTasksOnePerNumberRow struct {
	ID     uuid.UUID `json:"id"`
	Number int32     `json:"number"`
}

// One random active task per number for a subject: a classic random variant.
func (q *Queries) RandomTasksOnePerNumber(ctx context.Context, subjectID uuid.UUID) ([]RandomTasksOnePerNumberRow, error) {
	rows, err := q.db.Query(ctx, randomTasksOnePerNumber, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RandomTasksOnePerNumberRow{}
	for rows.Next() {
		var i RandomTasksOnePerNumberRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskStatus = `-- name: SetTaskStatus :one
UPDATE tasks SET status = $2 WHERE id = $1 RETURNING id, subject_id, number, statement, media, answer_schema, source, status, created_at
`

type SetTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Number,
		&i.Statement,
		&i.Media,
		&i.AnswerSchema,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const taskCountsByNumber = `-- name: TaskCountsByNumber :many
SELECT number,
       COUNT(*) FILTER (WHERE status = 'active')::bigint AS active,
       COUNT(*)::bigint AS total
FROM tasks
WHERE subject_id = $1
GROUP BY number
ORDER BY number
`

type TaskCountsByNumberRow struct {
	Number int32 `json:"number"`
	Active int64 `json:"active"`
	Total  int64 `json:"total"`
}

// Per-номер bank availability for a subject: how many tasks total and how many
// are ACTIVE (usable in a generated variant). Powers the composed-variant
// builder's availability hints.
func (q *Queries) TaskCountsByNumber(ctx context.Context, subjectID uuid.UUID) ([]TaskCountsByNumberRow, error) {
	rows, err := q.db.Query(ctx, taskCountsByNumber, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCountsByNumberRow{}
	for rows.Next() {
		var i TaskCountsByNumberRow
		if err := rows.Scan(&i.Number, &i.Active, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskExistsBySource = `-- name: TaskExistsBySource :one
SELECT EXISTS (
    SELECT 1 FROM tasks
    WHERE source ->> 'provider'  = $1::text
      AND source ->> 'extern_id' = $2::text
)
`

type TaskExistsBySourceParams struct {
	Provider string `json:"provider"`
	ExternID string `json:"extern_id"`
}

func (q *Queries) TaskExistsBySource(ctx context.Context, arg TaskExistsBySourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, taskExistsBySource, arg.Provider, arg.ExternID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTaskAnswer = `-- name: UpdateTaskAnswer :one
UPDATE tasks SET answer_schema = $2 WHERE id = $1 RETURNING id, subject_id, number, statement, media, answer_schema, source, status, created_at
`

type UpdateTaskAnswerParams struct {
	ID           uuid.UUID `json:"id"`
	AnswerSchema []byte    `json:"answer_schema"`
}

func (q *Queries) UpdateTaskAnswer(ctx context.Context, arg UpdateTaskAnswerParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAnswer, arg.ID, arg.AnswerSchema)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Number,
		&i.Statement,
		&i.Media,
		&i.AnswerSchema,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskContent = `-- name: UpdateTaskContent :one
UPDATE tasks SET statement = $2, media = $3 WHERE id = $1 RETURNING id, subject_id, number, statement, media, answer_schema, source, status, created_at
`

type UpdateTaskContentParams struct {
	ID        uuid.UUID `json:"id"`
	Statement string    `json:"statement"`
	Media     []byte    `json:"media"`
}

// Refresh a task's statement + media in place (re-fetch/upgrade), leaving its
// curated answer_schema and status untouched.
func (q *Queries) UpdateTaskContent(ctx context.Context, arg UpdateTaskContentParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskContent, arg.ID, arg.Statement, arg.Media)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Number,
		&i.Statement,
		&i.Media,
		&i.AnswerSchema,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
