// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTelegramLinkCode = `-- name: CreateTelegramLinkCode :one
INSERT INTO telegram_link_codes (code, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING code, user_id, expires_at, used_at, created_at
`

type CreateTelegramLinkCodeParams struct {
	Code      string    `json:"code"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTelegramLinkCode(ctx context.Context, arg CreateTelegramLinkCodeParams) (TelegramLinkCode, error) {
	row := q.db.QueryRow(ctx, createTelegramLinkCode, arg.Code, arg.UserID, arg.ExpiresAt)
	var i TelegramLinkCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidTelegramLinkCode = `-- name: GetValidTelegramLinkCode :one
SELECT code, user_id, expires_at, used_at, created_at FROM telegram_link_codes
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetValidTelegramLinkCode(ctx context.Context, code string) (TelegramLinkCode, error) {
	row := q.db.QueryRow(ctx, getValidTelegramLinkCode, code)
	var i TelegramLinkCode
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkTelegramToUser = `-- name: LinkTelegramToUser :one
UPDATE users SET telegram_id = $2 WHERE id = $1
RETURNING id, role, telegram_id, name, created_at, username, password_hash
`

type LinkTelegramToUserParams struct {
	ID         uuid.UUID `json:"id"`
	TelegramID *int64    `json:"telegram_id"`
}

func (q *Queries) LinkTelegramToUser(ctx context.Context, arg LinkTelegramToUserParams) (User, error) {
	row := q.db.QueryRow(ctx, linkTelegramToUser, arg.ID, arg.TelegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const markTelegramLinkCodeUsed = `-- name: MarkTelegramLinkCodeUsed :exec
UPDATE telegram_link_codes SET used_at = now() WHERE code = $1
`

func (q *Queries) MarkTelegramLinkCodeUsed(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, markTelegramLinkCodeUsed, code)
	return err
}
