// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTestItem = `-- name: AddTestItem :one
INSERT INTO test_items (test_id, task_id, position)
VALUES ($1, $2, $3)
RETURNING id, test_id, task_id, position
`

type AddTestItemParams struct {
	TestID   uuid.UUID `json:"test_id"`
	TaskID   uuid.UUID `json:"task_id"`
	Position int32     `json:"position"`
}

func (q *Queries) AddTestItem(ctx context.Context, arg AddTestItemParams) (TestItem, error) {
	row := q.db.QueryRow(ctx, addTestItem, arg.TestID, arg.TaskID, arg.Position)
	var i TestItem
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.TaskID,
		&i.Position,
	)
	return i, err
}

const createTest = `-- name: CreateTest :one
INSERT INTO tests (subject_id, kind, title, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, subject_id, kind, title, created_by, created_at, variant_of
`

type CreateTestParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Kind      string    `json:"kind"`
	Title     string    `json:"title"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.SubjectID,
		arg.Kind,
		arg.Title,
		arg.CreatedBy,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VariantOf,
	)
	return i, err
}

const deleteAssignmentsByTest = `-- name: DeleteAssignmentsByTest :exec
DELETE FROM assignments WHERE test_id = $1
`

func (q *Queries) DeleteAssignmentsByTest(ctx context.Context, testID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignmentsByTest, testID)
	return err
}

const deleteTest = `-- name: DeleteTest :execrows
DELETE FROM tests WHERE id = $1
`

func (q *Queries) DeleteTest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPracticeTest = `-- name: GetPracticeTest :one
SELECT id, subject_id, kind, title, created_by, created_at, variant_of FROM tests
WHERE subject_id = $1 AND created_by = $2 AND kind = 'drill' AND title = '__practice__'
LIMIT 1
`

type GetPracticeTestParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// Reusable ad-hoc practice test per (subject, owner) for bot/web free-solving.
func (q *Queries) GetPracticeTest(ctx context.Context, arg GetPracticeTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, getPracticeTest, arg.SubjectID, arg.CreatedBy)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VariantOf,
	)
	return i, err
}

const getTest = `-- name: GetTest :one
SELECT id, subject_id, kind, title, created_by, created_at, variant_of FROM tests WHERE id = $1
`

func (q *Queries) GetTest(ctx context.Context, id uuid.UUID) (Test, error) {
	row := q.db.QueryRow(ctx, getTest, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VariantOf,
	)
	return i, err
}

const listTestItems = `-- name: ListTestItems :many
SELECT ti.id, ti.test_id, ti.task_id, ti.position, t.subject_id, t.number, t.statement, t.media, t.answer_schema, t.status
FROM test_items ti
JOIN tasks t ON t.id = ti.task_id
WHERE ti.test_id = $1
ORDER BY ti.position
`

type ListTestItemsRow struct {
	ID           uuid.UUID `json:"id"`
	TestID       uuid.UUID `json:"test_id"`
	TaskID       uuid.UUID `json:"task_id"`
	Position     int32     `json:"position"`
	SubjectID    uuid.UUID `json:"subject_id"`
	Number       int32     `json:"number"`
	Statement    string    `json:"statement"`
	Media        []byte    `json:"media"`
	AnswerSchema []byte    `json:"answer_schema"`
	Status       string    `json:"status"`
}

func (q *Queries) ListTestItems(ctx context.Context, testID uuid.UUID) ([]ListTestItemsRow, error) {
	rows, err := q.db.Query(ctx, listTestItems, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestItemsRow{}
	for rows.Next() {
		var i ListTestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.TaskID,
			&i.Position,
			&i.SubjectID,
			&i.Number,
			&i.Statement,
			&i.Media,
			&i.AnswerSchema,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTests = `-- name: ListTests :many
SELECT id, subject_id, kind, title, created_by, created_at, variant_of FROM tests
WHERE ($1::uuid IS NULL OR subject_id = $1)
  AND variant_of IS NULL
ORDER BY created_at DESC
`

// Per-student variant clones (variant_of set) are working copies, not the
// teacher's library — keep them out of the builder/assign lists.
func (q *Queries) ListTests(ctx context.Context, subjectID *uuid.UUID) ([]Test, error) {
	rows, err := q.db.Query(ctx, listTests, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Test{}
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Kind,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VariantOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestVariantOf = `-- name: SetTestVariantOf :exec
UPDATE tests SET variant_of = $2 WHERE id = $1
`

type SetTestVariantOfParams struct {
	ID        uuid.UUID  `json:"id"`
	VariantOf *uuid.UUID `json:"variant_of"`
}

func (q *Queries) SetTestVariantOf(ctx context.Context, arg SetTestVariantOfParams) error {
	_, err := q.db.Exec(ctx, setTestVariantOf, arg.ID, arg.VariantOf)
	return err
}

const testHasAttempts = `-- name: TestHasAttempts :one
SELECT EXISTS (SELECT 1 FROM attempts WHERE test_id = $1)
`

// A test that has been attempted (assigned+solved or self-practice) is in use
// and must not be silently deleted — deleting would orphan student history.
func (q *Queries) TestHasAttempts(ctx context.Context, testID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, testHasAttempts, testID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTestTitle = `-- name: UpdateTestTitle :one
UPDATE tests SET title = $2 WHERE id = $1 RETURNING id, subject_id, kind, title, created_by, created_at, variant_of
`

type UpdateTestTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateTestTitle(ctx context.Context, arg UpdateTestTitleParams) (Test, error) {
	row := q.db.QueryRow(ctx, updateTestTitle, arg.ID, arg.Title)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VariantOf,
	)
	return i, err
}
