// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (teacher_id, student_id)
VALUES ($1, $2)
ON CONFLICT (teacher_id, student_id) DO UPDATE SET teacher_id = EXCLUDED.teacher_id
RETURNING id, teacher_id, student_id
`

type CreateEnrollmentParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment, arg.TeacherID, arg.StudentID)
	var i Enrollment
	err := row.Scan(&i.ID, &i.TeacherID, &i.StudentID)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (role, telegram_id, name)
VALUES ($1, $2, $3)
RETURNING id, role, telegram_id, name, created_at, username, password_hash
`

type CreateUserParams struct {
	Role       string `json:"role"`
	TelegramID *int64 `json:"telegram_id"`
	Name       string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Role, arg.TelegramID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const createUserWithCredentials = `-- name: CreateUserWithCredentials :one
INSERT INTO users (role, name, username, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, role, telegram_id, name, created_at, username, password_hash
`

type CreateUserWithCredentialsParams struct {
	Role         string  `json:"role"`
	Name         string  `json:"name"`
	Username     *string `json:"username"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) CreateUserWithCredentials(ctx context.Context, arg CreateUserWithCredentialsParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithCredentials,
		arg.Role,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, role, telegram_id, name, created_at, username, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByTelegram = `-- name: GetUserByTelegram :one
SELECT id, role, telegram_id, name, created_at, username, password_hash FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegram(ctx context.Context, telegramID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegram, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, telegram_id, name, created_at, username, password_hash FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const idleStudents = `-- name: IdleStudents :many
SELECT u.id, u.telegram_id, u.name
FROM users u
JOIN attempts att ON att.student_id = u.id
JOIN answers  a   ON a.attempt_id = att.id
WHERE u.role = 'student'
GROUP BY u.id
HAVING max(a.answered_at) < $1
`

type IdleStudentsRow struct {
	ID         uuid.UUID `json:"id"`
	TelegramID *int64    `json:"telegram_id"`
	Name       string    `json:"name"`
}

// Students who have answered before but not since $1 (for streak nudges).
func (q *Queries) IdleStudents(ctx context.Context, idleSince time.Time) ([]IdleStudentsRow, error) {
	rows, err := q.db.Query(ctx, idleStudents, idleSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdleStudentsRow{}
	for rows.Next() {
		var i IdleStudentsRow
		if err := rows.Scan(&i.ID, &i.TelegramID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, role, telegram_id, name, created_at, username, password_hash FROM users WHERE role = 'student' ORDER BY name
`

func (q *Queries) ListStudents(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForTeacher = `-- name: ListStudentsForTeacher :many
SELECT u.id, u.role, u.telegram_id, u.name, u.created_at, u.username, u.password_hash FROM users u
JOIN enrollments e ON e.student_id = u.id
WHERE e.teacher_id = $1
ORDER BY u.name
`

func (q *Queries) ListStudentsForTeacher(ctx context.Context, teacherID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudentsForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
