// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND is_active
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (teacher_id, student_id)
VALUES ($1, $2)
ON CONFLICT (teacher_id, student_id) DO UPDATE SET teacher_id = EXCLUDED.teacher_id
RETURNING id, teacher_id, student_id
`

type CreateEnrollmentParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment, arg.TeacherID, arg.StudentID)
	var i Enrollment
	err := row.Scan(&i.ID, &i.TeacherID, &i.StudentID)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (role, telegram_id, name)
VALUES ($1, $2, $3)
RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type CreateUserParams struct {
	Role       string `json:"role"`
	TelegramID *int64 `json:"telegram_id"`
	Name       string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Role, arg.TelegramID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const createUserWithCredentials = `-- name: CreateUserWithCredentials :one
INSERT INTO users (role, name, username, password_hash, subject)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type CreateUserWithCredentialsParams struct {
	Role         string  `json:"role"`
	Name         string  `json:"name"`
	Username     *string `json:"username"`
	PasswordHash *string `json:"password_hash"`
	Subject      *string `json:"subject"`
}

func (q *Queries) CreateUserWithCredentials(ctx context.Context, arg CreateUserWithCredentialsParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithCredentials,
		arg.Role,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Subject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :execrows
DELETE FROM enrollments WHERE teacher_id = $1 AND student_id = $2
`

type DeleteEnrollmentParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	StudentID uuid.UUID `json:"student_id"`
}

// Drops the teacher↔student link ("отчислить"). History (attempts,
// assignments) is untouched; other teachers' enrollments stay.
func (q *Queries) DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnrollment, arg.TeacherID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, role, telegram_id, name, created_at, username, password_hash, is_active, subject FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const getUserByTelegram = `-- name: GetUserByTelegram :one
SELECT id, role, telegram_id, name, created_at, username, password_hash, is_active, subject FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegram(ctx context.Context, telegramID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegram, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, telegram_id, name, created_at, username, password_hash, is_active, subject FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const idleStudents = `-- name: IdleStudents :many
SELECT u.id, u.telegram_id, u.name
FROM users u
JOIN attempts att ON att.student_id = u.id
JOIN answers  a   ON a.attempt_id = att.id
WHERE u.role = 'student' AND u.is_active
GROUP BY u.id
HAVING max(a.answered_at) < $1
`

type IdleStudentsRow struct {
	ID         uuid.UUID `json:"id"`
	TelegramID *int64    `json:"telegram_id"`
	Name       string    `json:"name"`
}

// Students who have answered before but not since $1 (for streak nudges).
func (q *Queries) IdleStudents(ctx context.Context, idleSince time.Time) ([]IdleStudentsRow, error) {
	rows, err := q.db.Query(ctx, idleStudents, idleSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdleStudentsRow{}
	for rows.Next() {
		var i IdleStudentsRow
		if err := rows.Scan(&i.ID, &i.TelegramID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeacherOfStudent = `-- name: IsTeacherOfStudent :one
SELECT EXISTS(
    SELECT 1 FROM enrollments WHERE teacher_id = $1 AND student_id = $2
) AS enrolled
`

type IsTeacherOfStudentParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	StudentID uuid.UUID `json:"student_id"`
}

// The teacher↔student link every per-student authorization runs on.
func (q *Queries) IsTeacherOfStudent(ctx context.Context, arg IsTeacherOfStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherOfStudent, arg.TeacherID, arg.StudentID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const listActiveAdminIDs = `-- name: ListActiveAdminIDs :many
SELECT id FROM users WHERE role = 'admin' AND is_active
`

func (q *Queries) ListActiveAdminIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, role, telegram_id, name, created_at, username, password_hash, is_active, subject FROM users WHERE role = 'student' ORDER BY name
`

func (q *Queries) ListStudents(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsActive,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForTeacher = `-- name: ListStudentsForTeacher :many
SELECT u.id, u.role, u.telegram_id, u.name, u.created_at, u.username, u.password_hash, u.is_active, u.subject FROM users u
JOIN enrollments e ON e.student_id = u.id
WHERE e.teacher_id = $1
ORDER BY u.name
`

func (q *Queries) ListStudentsForTeacher(ctx context.Context, teacherID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudentsForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsActive,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherIDsForStudent = `-- name: ListTeacherIDsForStudent :many
SELECT teacher_id FROM enrollments WHERE student_id = $1
`

// Reverse enrollment lookup: who teaches this student (the recipients of the
// «забыл пароль» notification).
func (q *Queries) ListTeacherIDsForStudent(ctx context.Context, studentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeacherIDsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var teacher_id uuid.UUID
		if err := rows.Scan(&teacher_id); err != nil {
			return nil, err
		}
		items = append(items, teacher_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForStudent = `-- name: ListTeachersForStudent :many
SELECT u.id, u.role, u.telegram_id, u.name, u.created_at, u.username, u.password_hash, u.is_active, u.subject FROM users u
JOIN enrollments e ON e.teacher_id = u.id
WHERE e.student_id = $1
ORDER BY u.name
`

// All teachers a student is enrolled to (a student may have several — school
// teacher + репетитор). Powers the student profile's "мои учителя".
func (q *Queries) ListTeachersForStudent(ctx context.Context, studentID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listTeachersForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsActive,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, role, telegram_id, name, created_at, username, password_hash, is_active, subject FROM users
ORDER BY CASE role WHEN 'admin' THEN 0 WHEN 'teacher' THEN 1 ELSE 2 END, name
`

// Admin panel: every account, admins/teachers first.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TelegramID,
			&i.Name,
			&i.CreatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsActive,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET is_active = $2 WHERE id = $1 RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const setUserName = `-- name: SetUserName :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type SetUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserRoleSubject = `-- name: SetUserRoleSubject :one
UPDATE users SET role = $2, subject = $3 WHERE id = $1 RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type SetUserRoleSubjectParams struct {
	ID      uuid.UUID `json:"id"`
	Role    string    `json:"role"`
	Subject *string   `json:"subject"`
}

func (q *Queries) SetUserRoleSubject(ctx context.Context, arg SetUserRoleSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRoleSubject, arg.ID, arg.Role, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}

const setUserSubject = `-- name: SetUserSubject :one
UPDATE users SET subject = $2 WHERE id = $1 RETURNING id, role, telegram_id, name, created_at, username, password_hash, is_active, subject
`

type SetUserSubjectParams struct {
	ID      uuid.UUID `json:"id"`
	Subject *string   `json:"subject"`
}

func (q *Queries) SetUserSubject(ctx context.Context, arg SetUserSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserSubject, arg.ID, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.TelegramID,
		&i.Name,
		&i.CreatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.Subject,
	)
	return i, err
}
